ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'RECIBIDO_POR_INVENTARIO';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'PREPARANDO';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'ENTREGADO';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'RECIBIDO_POR_TIENDA';
